# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationRecette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('difficulte', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='preparationrecette',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='recettes.Recette'),
        ),
    ]
