# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_auto_20170129_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.BooleanField(),
        ),
    ]
