# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0006_auto_20170228_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calorie',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
