# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0011_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='blank.png', upload_to='photos'),
        ),
    ]
