# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0012_auto_20170301_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
    ]
