# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0013_auto_20170302_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recettes.Preparation')),
            ],
        ),
    ]
