# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0014_etapepreparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapepreparation',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
