# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0015_etapepreparation_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='portion',
            field=models.IntegerField(default=1),
        ),
    ]
