# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pu', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='nom',
            new_name='code',
        ),
        migrations.AddField(
            model_name='element',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recettes.Ingredient'),
        ),
        migrations.AddField(
            model_name='element',
            name='preparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='recettes.Preparation'),
        ),
        migrations.AddField(
            model_name='preparationrecette',
            name='preparation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='recettes.Preparation'),
            preserve_default=False,
        ),
    ]
