# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_auto_20170129_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationrecette',
            name='preparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Preparation'),
        ),
    ]
