# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_auto_20170228_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergene',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
