# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0008_categorie'),
    ]

    operations = [
        migrations.RunSQL(
    	[("INSERT INTO recettes_categorie (code, description) VALUES (%s,%s);", ['divers', 'catégorie non définie'])]
	),
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recettes.Categorie'),
        ),
    ]
