# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0010_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='photos/blank.png', upload_to='photos'),
        ),
    ]
