# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0016_recette_portion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeRecette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recettes.Recette')),
            ],
        ),
    ]
