# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0017_etaperecette'),
    ]

    operations = [
         migrations.RenameField('Recette', 'description', 'titre'),
    ]
