# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0018_auto_20170309_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='bonasavoir',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='preparation',
            name='bonasavoir',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='preparation',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recette',
            name='bonasavoir',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='recette',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='etapepreparation',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='etaperecette',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
