# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0019_auto_20170309_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='bonasavoir',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='blank.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='bonasavoir',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='recette',
            name='bonasavoir',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
