# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recettes', '0020_auto_20180629_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
    ]
