# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0022_auto_20180704_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
    ]
