# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0026_auto_20180706_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fibres_alimentaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glucides',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glucidesDontSucres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glucides_inferieures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kcalories',
            field=models.IntegerField(default=0, verbose_name='Kilo calories'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kjoules',
            field=models.IntegerField(default=0, verbose_name='Kilo joules'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='matieges_grasses_inferieures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='matieres_grasses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='matieres_grasses_saturees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sel_inferieur',
            field=models.BooleanField(default=False),
        ),
    ]
