# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0027_auto_20180706_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='glucidesDontSucres',
            new_name='glucides_dont_sucres',
        ),
    ]
