# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0028_auto_20180706_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='proteines_inferieur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
