# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0029_auto_20180706_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fibres_inferieur',
            field=models.BooleanField(default=False),
        ),
    ]
