# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0030_ingredient_fibres_inferieur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='matieres_grasses_saturees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Dont acides gras satur\xe9s'),
        ),
    ]
