# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recettes', '0031_auto_20180706_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('owner', 'code')]),
        ),
    ]
