# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0033_auto_20180706_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='acces',
            field=models.CharField(choices=[('PUB', 'public'), ('PRIV', 'prive')], default='PUB', max_length=4),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.Photo'),
        ),
    ]
