# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0036_auto_20180708_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Photo'),
        ),
    ]
