# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0038_ingredient_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='acces',
            field=models.CharField(choices=[('PUB', 'public'), ('PRIV', 'priv\xe9')], default='PUB', max_length=4),
        ),
    ]
