# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0044_auto_20180709_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.BinaryField(null=True),
        ),
    ]
