# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0045_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
