# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0046_auto_20180715_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='date_modification',
            field=models.DateField(auto_now=True),
        ),
    ]
