# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0047_auto_20180721_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
