# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0050_auto_20180722_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='fibres_alimentaires',
            new_name='fibres',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='fibres_inferieur',
            new_name='fibres_inferieures',
        ),
    ]
