# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0053_auto_20180722_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapepreparation',
            name='acces',
        ),
        migrations.RemoveField(
            model_name='etapepreparation',
            name='owner',
        ),
    ]
