# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0054_auto_20180723_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='groupe',
            field=models.CharField(choices=[('MAT', 'mat\xe9riel'), ('PREP', 'pr\xe9parations'), ('ING', 'ingr\xe9dients'), ('REC', 'recettes')], default='ING', max_length=10),
        ),
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Categorie'),
        ),
    ]
