# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0056_photo_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='code',
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='groupe',
            field=models.CharField(choices=[('REC', 'recettes'), ('ING', 'ingr\xe9dients'), ('PREP', 'pr\xe9parations'), ('MAT', 'mat\xe9riel')], default='ING', max_length=10),
        ),
    ]
