# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recettes', '0057_auto_20180726_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='acces',
            field=models.CharField(choices=[('PUB', 'public'), ('PRIV', 'priv\xe9')], default='PUB', max_length=4),
        ),
        migrations.AddField(
            model_name='categorie',
            name='owner',
            field=models.ForeignKey(default='anonyme', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acces',
            field=models.CharField(choices=[('PUB', 'public'), ('PRIV', 'priv\xe9')], default='PRIV', max_length=4),
        ),
    ]
