# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0059_auto_20180727_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
