# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0061_auto_20180727_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='groupe',
            field=models.CharField(choices=[('REC', 'recettes'), ('ING', 'ingr\xe9dients'), ('PREP', 'pr\xe9parations'), ('MAT', 'mat\xe9riel'), ('SANS', 'non affect\xe9')], default='ING', max_length=10),
        ),
    ]
