# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0063_auto_20180727_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together=set([]),
        ),
    ]
