# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0065_auto_20180727_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Categorie'),
        ),
    ]
