# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0066_ingredient_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pp',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=6),
        ),
    ]
