# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0067_ingredient_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fibres_alimentaires',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='glucides',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='glucides_dont_sucres',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='matieres_grasses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteines',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sel',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
