# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0069_auto_20180729_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='groupe',
            field=models.CharField(choices=[('REC', 'recettes'), ('ING', 'ingr\xe9dients'), ('PREP', 'pr\xe9parations'), ('MAT', 'mat\xe9riel'), ('SANS', 'non affect\xe9')], default='SANS', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Photo'),
        ),
    ]
