# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0070_auto_20180729_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Categorie'),
        ),
    ]
