# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0071_preparation_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Ingredient'),
        ),
    ]
