# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0072_auto_20180806_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapepreparation',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='etaperecette',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='preparation',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='titre',
            new_name='nom',
        ),
    ]
