# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recettes', '0074_etapepreparation_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=100)),
                ('acces', models.CharField(choices=[('PUB', 'public'), ('PRIV', 'priv\xe9')], default='PUB', max_length=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Preparation')),
                ('owner', models.ForeignKey(default='anonyme', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='recettes.Preparation')),
            ],
        ),
    ]
