# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recettes', '0076_auto_20180819_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementRecette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('acces', models.CharField(choices=[('PUB', 'public'), ('PRIV', 'priv\xe9')], default='PRIV', max_length=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.Ingredient')),
                ('owner', models.ForeignKey(default='anonyme', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='recettes.Recette')),
            ],
        ),
    ]
